package comp9322.assignment1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-10-12T18:10:01.823+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://assignment1.comp9322", name = "EmployeeValidationService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EmployeeValidationService {

    @WebResult(name = "CheckEmailAddressResponse", targetNamespace = "http://assignment1.comp9322", partName = "parameters")
    @WebMethod(operationName = "CheckEmailAddress", action = "http://assignment1.comp9322/CheckEmailAddress")
    public CheckEmailAddressResponse checkEmailAddress(
        @WebParam(partName = "parameters", name = "CheckEmailAddressRequest", targetNamespace = "http://assignment1.comp9322")
        CheckEmailAddressRequest parameters
    );

    @WebResult(name = "CheckAddressResponse", targetNamespace = "http://assignment1.comp9322", partName = "parameters")
    @WebMethod(operationName = "CheckAddress", action = "http://assignment1.comp9322/CheckAddress")
    public CheckAddressResponse checkAddress(
        @WebParam(partName = "parameters", name = "CheckAddressRequest", targetNamespace = "http://assignment1.comp9322")
        CheckAddressRequest parameters
    ) throws ValidationFaultMsg;

    @WebResult(name = "ReturnPostcodeResponse", targetNamespace = "http://assignment1.comp9322", partName = "parameters")
    @WebMethod(operationName = "ReturnPostcode", action = "http://assignment1.comp9322/ReturnPostcode")
    public ReturnPostcodeResponse returnPostcode(
        @WebParam(partName = "parameters", name = "ReturnPostcodeRequest", targetNamespace = "http://assignment1.comp9322")
        ReturnPostcodeRequest parameters
    ) throws ValidationFaultMsg;
}
